### ISSUE TITLE
Memory consumption issue of `xbps-remove`

### ISSUE THREAD

**Issue by CasperVector** [void-linux/xbps#182]
When the number of packages to be removed is fairly large, `xbps-remove` can consume a lot of memory:
* Just with a few scores of obsolete packages and orphans, the 8G memory on my machine is often eaten up by `xbps-remove -Oo`.
* I then try to limit the memory consumption of `xbps-remove` with `s6-softlimit`, but according to a  test done on my machine just now, even 24 obsolete packages cause `s6-softlimit -m 8000000000 xbps-remove -nO` (8G memory) to reproducibly segfault.

According to valgrind, the segfault occurs because of the failure to handle null `thd[i].thread` in `xbps_array_foreach_cb_multi()` from `lib/plist.c`, and the null thread pointers occured in turn due to insufficient memory when calling `pthread_create()`.

When forcing `maxthreads = 1` in `xbps_array_foreach_cb_multi()`, `s6-softlimit -m 20000000 xbps-remove -nOo` (20M memory) causes `xbps-remove` to complain `ERROR: cannot access to pkgdb: Cannot allocate memory`, but works as expected with higher memory limits.

Please feel free to ask me for more information if necessary.

**Comment by xtraeme** [comment]
could you please share the output of `xbps-remove -v` ?

**Comment by CasperVector** [comment]
I ran `xbps-remove -Oo` with `maxthreads = 1` yesterday, and therefore cannot reproduce the problem for now.  I will try this the next time enough obsolete/orphan packages have been gathered.

**Comment by CasperVector** [comment]
The problem can be reproduced again now.
`xbps-remove -V` outputs `XBPS: 0.57.1 API: 20190707 GIT: 85b8b3bb`.
I will keep the obsolete/orphan packages for a few days; please feel free to ask for more information.

**Comment by xtraeme** [comment]
so the issue only appears when `maxthreads` > 1 ?

**Comment by CasperVector** [comment]
Yes, at least according to my observation.

**Comment by xtraeme** [comment]
can you please paste relevant valgrind output? where's the origin for the memleak?

**Comment by CasperVector** [comment]
Output of `s6-softlimit -m 8000000000 valgrind --leak-check=full --leak-check=full --show-leak-kinds=all xbps-remove -nOo` with `maxthreads = (int)sysconf(_SC_NPROCESSORS_ONLN)`: [xbps.log](https://github.com/void-linux/xbps/files/4005344/xbps.log).

Output of `s6-softlimit -m 200000000 valgrind --leak-check=full --leak-check=full --show-leak-kinds=all xbps-remove -nOo` with `maxthreads = 1`: [xbps.log](https://github.com/void-linux/xbps/files/4005331/xbps.log).  (With larger memory, `xbps-remove` runs very slowly and seems to never end.)

**Comment by xtraeme** [comment]
Please try with the latest xbps from git/master. The issue with pthread_create() should now be fixed. But the memleak must be somewhere.

**Comment by CasperVector** [comment]
Sorry, but the segfault persists, because the "wait for all threads" loop is not skipped on error...

**Comment by xtraeme** [comment]
http://dpaste.com/3R4VRSW.txt

please try this one

**Comment by CasperVector** [comment]
Many thanks :) now it at least correctly bail out.

**Comment by xtraeme** [comment]
Anyway I'd like to know what's the cause to hit such high memory usage.

**Comment by CasperVector** [comment]
Me too :)  And on a second thought, you may also consider reusing the variable `i' between the `pthread_create()` and `pthread_join()` loops, so that only the successfully created loops are joined.

**Comment by xtraeme** [comment]
indeed

**Comment by xtraeme** [comment]
http://dpaste.com/3W8BQ7P.txt

**Comment by CasperVector** [comment]
But then you need to remove the `goto` and the `out` label...

**Comment by xtraeme** [comment]
I did already, it's in master

**Comment by xtraeme** [comment]
Pushed now, I thought it was there before... my fault :-)

**Comment by xtraeme** [comment]
Please note that the issue (which I can't reproduce) is specific to `xbps-remove -O` (clean repocache).

**Comment by CasperVector** [comment]
`xbps-remove -o` (remove orphans) seems to be affected in another way: `s6-softlimit -m 20000000 xbps-remove -no` errors out with `ERROR: cannot access to pkgdb: Cannot allocate memory` (but works as expected with more memory), while `s6-softlimit -m 220000000 valgrind xbps-remove -no` gives (but works as expected with more memory, and valgrind complains about insufficient memory with less memory)
```
==5906== Memcheck, a memory error detector
==5906== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==5906== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==5906== Command: xbps-remove -no
==5906== 
Unexpected error.
==5906== 
==5906== Process terminating with default action of signal 6 (SIGABRT)
==5906==    at 0x4C3D931: raise (raise.c:51)
==5906==    by 0x4C2755A: abort (abort.c:79)
==5906==    by 0x4C2742E: __assert_fail_base.cold (assert.c:92)
==5906==    by 0x4C36111: __assert_fail (assert.c:101)
==5906==    by 0x48634EE: get_pkg_in_array.lto_priv.0 (in /home/casper/var/tmp/xbps/image/usr/lib/libxbps.so.4.0.1)
==5906==    by 0x4873B15: xbps_find_pkg_orphans (in /home/casper/var/tmp/xbps/image/usr/lib/libxbps.so.4.0.1)
==5906==    by 0x486792D: xbps_transaction_autoremove_pkgs (in /home/casper/var/tmp/xbps/image/usr/lib/libxbps.so.4.0.1)
==5906==    by 0x10A955: main (main.c:276)
==5906== 
==5906== HEAP SUMMARY:
==5906==     in use at exit: 3,372,974 bytes in 59,666 blocks
==5906==   total heap usage: 729,612 allocs, 669,946 frees, 15,216,221 bytes allocated
==5906== 
==5906== LEAK SUMMARY:
==5906==    definitely lost: 1,850 bytes in 121 blocks
==5906==    indirectly lost: 9,105 bytes in 261 blocks
==5906==      possibly lost: 0 bytes in 0 blocks
==5906==    still reachable: 3,362,019 bytes in 59,284 blocks
==5906==         suppressed: 0 bytes in 0 blocks
==5906== Rerun with --leak-check=full to see details of leaked memory
==5906== 
==5906== For lists of detected and suppressed errors, rerun with: -s
==5906== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by xtraeme** [comment]
hmmm

**Comment by xtraeme** [comment]
please try this one: http://dpaste.com/00DWPJE.txt

**Comment by CasperVector** [comment]
The exactly same symptoms persist with that patch...

**Comment by xtraeme** [comment]
is this still reproducible? how many threads are used in your system?

**Comment by CasperVector** [comment]
With the latest release in the Void package repository (`XBPS: 0.58 API: 20200118 GIT: UNSET`):
```
% xbps-remove -nO | wc -l
0
% s6-softlimit -m 16000000 xbps-remove -nO | wc -l
0
% s6-softlimit -m 15000000 xbps-remove -nO
xbps-remove: error while loading shared libraries: libattr.so.1: failed to map segment from shared object

% xbps-remove -no | wc -l
11
% s6-softlimit -m 22000000 xbps-remove -no | wc -l
11
% s6-softlimit -m 21000000 xbps-remove -no
ERROR: cannot access to pkgdb: Cannot allocate memory
% s6-softlimit -m 140000000 valgrind xbps-remove -no
[...]
Unexpected error.
[...]
% s6-softlimit -m 130000000 valgrind xbps-remove -no
[...]
==30738==     Valgrind's memory management: out of memory:
[...]
```

With the latest git head (6ff94221):
```
% valgrind xbps-remove -nO
[...]
==32126== Process terminating with default action of signal 11 (SIGSEGV)
==32126==  General Protection Fault
==32126==    at 0x483AD03: strcmp (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==32126==    by 0x485FF0E: xbps_pkg_arch_match (in /home/casper/var/tmp/xbps/image/usr/lib/libxbps.so.4.1.0)
==32126==    by 0x10BC02: cleaner_cb (clean-cache.c:58)
==32126==    by 0x48638A2: array_foreach_thread (in /home/casper/var/tmp/xbps/image/usr/lib/libxbps.so.4.1.0)
==32126==    by 0x490DF26: start_thread (pthread_create.c:479)
==32126==    by 0x4CFFE0E: clone (clone.S:95)
[...]
% valgrind xbps-remove -no
[...]
==3543== Process terminating with default action of signal 11 (SIGSEGV)
==3543==  Access not within mapped region at address 0x28
==3543==    at 0x49128B0: __pthread_rwlock_rdlock_full (pthread_rwlock_common.c:299)
==3543==    by 0x49128B0: pthread_rwlock_rdlock (pthread_rwlock_rdlock.c:27)
==3543==    by 0x4856822: xbps_dictionary_iterator (in /home/casper/var/tmp/xbps/image/usr/lib/libxbps.so.4.1.0)
==3543==    by 0x4873BBC: xbps_find_pkg_orphans (in /home/casper/var/tmp/xbps/image/usr/lib/libxbps.so.4.1.0)
==3543==    by 0x48677DD: xbps_transaction_autoremove_pkgs (in /home/casper/var/tmp/xbps/image/usr/lib/libxbps.so.4.1.0)
==3543==    by 0x10A955: main (main.c:276)
[...]
```

**Comment by xtraeme** [comment]
how many threads?

**Comment by CasperVector** [comment]
This time I did not patch anything, so `maxthreads = (int)sysconf(_SC_NPROCESSORS_ONLN)` (actually 4).

**Comment by xtraeme** [comment]
can you please do:

```
du -sh cachedir
```
?

**Comment by CasperVector** [comment]
```
% du -sh /var/cache/xbps
79M	/var/cache/xbps
```

**Comment by xtraeme** [comment]
hmmmm

**Comment by xtraeme** [comment]
so I should be able to reproduce it... I thought you'd have like 2TB of old pkgs...

**Comment by CasperVector** [comment]
I believe I mentioned it :)
```
% xbps-remove -no | wc -l
11
```

**Comment by xtraeme** [comment]
```
[juan@leysa ~]$ s6-softlimit -m 21000000 xbps-remove -c ~/projects/void-linux/void-packages/hostdir/repocache-x86_64-musl -no
[juan@leysa ~]$ echo $?
0
[juan@leysa ~]$ ls -l projects/void-linux/void-packages/hostdir/repocache-x86_64-musl|wc -l
1463
[juan@leysa ~]$
```

Can't reproduce it... my CPU also has 4 cores.

**Comment by CasperVector** [comment]
I will try to debug the problem on myself with my spare time, but I am not sure I can do it soon.

**Comment by xtraeme** [comment]
We've made a bunch of memory related changes in master, please update and report.

**Comment by CasperVector** [comment]
This time both `xbps-remove -no` and `xbps-remove -nO` work as expected.
But a more interesting thing is that commit 6ff94221 also works now for me; I do not know why.
I will try to give more information if the problems occurs again.

**Comment by xtraeme** [comment]
I know that maybe usage may be too high but this is due to repos being compressed in xz. With 0.59 it defaults to zstd. This would reduce memory usage a little bit. If you can reproduce high memory usage I'd like to know... Please get some details and report. Thanks

**Comment by CasperVector** [comment]
I have just did my routine update, and ran `xbps-remove`, but forgot to use the `-n` option, so the results cannot be produced again for now.  Anyway, here are the results:
* I ran `s6-softlimit -m 100000000 xbps-remove -Oo`, which exited 11.
* I then ran `s6-softlimit -d 100000000 xbps-remove -Oo`, which was killed by `SIGSEGV`.
* A second run of `s6-softlimit -d 100000000 xbps-remove -Oo' yielded the same result.
* A third run of `s6-softlimit -d 100000000 xbps-remove -Oo` resulted in `xbps-remove: portableproplib/prop_array.c:754: prop_array_remove: Assertion 'idx < pa->pa_count' failed`.
* A fourth run of `s6-softlimit -d 100000000 xbps-remove -Oo` yielded the same assertion failure.
* A fifth run of `s6-softlimit -d 100000000 xbps-remove -Oo` successfully cleaned the cache, and proceeded to ask me if orphaned were to be removed, which I chose not to do.
* Later runs of `s6-softlimit -d 100000000 xbps-remove -Oo` ran as expected, asking whether to remove orphans.
I will try `xbps-remove -n` on my next routine update.

**Comment by CasperVector** [comment]
The results of this time:
```
% export PATH="$(pwd)/image/usr/bin:$PATH"
% xbps-remove -V
XBPS: 0.59 API: 20200221 GIT: 40e14203
% s6-softlimit -d 200000000 gdb --args xbps-remove -nOo          
GNU gdb (GDB) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from xbps-remove...
(gdb) r
Starting program: /home/casper/var/tmp/xbps/image/usr/bin/xbps-remove -nOo
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff7152700 (LWP 26477)]
[New Thread 0x7fffee951700 (LWP 26478)]
[New Thread 0x7ffff6951700 (LWP 26479)]
[New Thread 0x7ffff6150700 (LWP 26480)]

Thread 5 "xbps-remove" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6150700 (LWP 26480)]
0x00007fffe5641bc0 in ?? ()
(gdb) bt
#0  0x00007fffe5641bc0 in ?? ()
#1  0x00007ffff7fb2297 in xbps_repo_close (repo=0x7fffe4013250) at repo.c:374
#2  0x00007ffff7fb2d3e in repo_open_with_type (xhp=xhp@entry=0x7fffffffd980, 
    url=url@entry=0x55555555e950 "https://mirrors.dotsrc.org/voidlinux/current", 
    name=name@entry=0x7ffff7fbee28 "repodata") at repo.c:259
#3  0x00007ffff7fb2f6c in xbps_repo_public_open (xhp=xhp@entry=0x7fffffffd980, 
    url=url@entry=0x55555555e950 "https://mirrors.dotsrc.org/voidlinux/current")
    at repo.c:333
#4  0x00007ffff7fb2f89 in xbps_repo_open (xhp=xhp@entry=0x7fffffffd980, 
    url=0x55555555e950 "https://mirrors.dotsrc.org/voidlinux/current")
    at repo.c:339
#5  0x00007ffff7fb3910 in xbps_rpool_foreach (xhp=xhp@entry=0x7fffffffd980, 
    fn=fn@entry=0x7ffff7fb33e0 <find_pkg_cb>, arg=arg@entry=0x7ffff614fe30)
    at rpool.c:153
#6  0x00007ffff7fb3b06 in repo_find_pkg (type=REAL_PKG, 
    pkg=0x7fffe4000bb0 "python3-jupyter_core-4.4.0_2", xhp=0x7fffffffd980)
    at rpool.c:297
#7  xbps_rpool_get_pkg (xhp=xhp@entry=0x7fffffffd980, 
    pkg=pkg@entry=0x7fffe4000bb0 "python3-jupyter_core-4.4.0_2") at rpool.c:334
#8  0x0000555555556c52 in cleaner_cb (xhp=0x7fffffffd980, obj=<optimized out>, 
    key=<optimized out>, arg=<optimized out>, done=<optimized out>)
    at clean-cache.c:70
#9  0x00007ffff7facbf3 in array_foreach_thread (arg=0x55555555ed80) at plist.c:82
#10 0x00007ffff7c18f27 in start_thread (arg=<optimized out>)
    at pthread_create.c:479
#11 0x00007ffff7b47e0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) quit
A debugging session is active.

	Inferior 1 [process 26473] will be killed.

Quit anyway? (y or n) y
```

**Comment by anaggh** [comment]
High CPU usage when running `xbps-remove -O`
![Peek 2020-03-27 20-52](https://user-images.githubusercontent.com/9278844/77772056-88f93100-706d-11ea-8d38-2eb0b1d8b2de.gif)

**Comment by Duncaen** [comment]
`xbps-remove -O` uses N threads (the number of cores you have) to go through all files in `/var/cache/xbps` and sha256 sums them, of course it consumes a lot of CPU to do this.

I guess we could change it to only sha256 sum each file with an extra flag, but I don't really think there is a need to really make this faster or less CPU intensive.
